services:
  local_dev_atlas:
    image: mongodb/mongodb-atlas-local:8.0
    hostname: local_dev_atlas
    ports:
      - 27017:27017
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=philoagents
      - MONGODB_INITDB_ROOT_PASSWORD=philoagents
    volumes:
      - data:/data/db
      - config:/data/configdb
  api:
    container_name: agent-backend
    build:
      context: .
      dockerfile: philoagents/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
  ui:
    container_name: philosopher-ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./ui:/app
      - /app/node_modules
    depends_on:
      - api

volumes:
  data:
  config: