# services:
#   api:
#     container_name: philoagents-api
#     build:
#       context: ./philoagents-api
#       dockerfile: Dockerfile
#     environment:
#       - MONGODB_URI=mongodb+srv://aatish9403:9403@cluster0.sgxa3pk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#     ports:
#       - "8000:8000"
#     env_file:
#       - ./philoagents-api/.env
#     networks:
#       - philoagents-network

#   ui:
#     container_name: philoagents-ui
#     build:
#       context: ./philoagents-ui
#       dockerfile: Dockerfile
#     ports:
#       - "8080:8080"
#     volumes:
#       - ./philoagents-ui:/app
#       - /app/node_modules
#     depends_on:
#       - api
#     networks:
#       - philoagents-network

# networks:
#   philoagents-network:
#     name: philoagents-network

version: "3.9"

services:
  api:
    container_name: philoagents-api
    build:
      context: ./philoagents-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./philoagents-api/.env
    environment:
      - MONGODB_URI=mongodb+srv://aatish9403:9403@cluster0.sgxa3pk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    volumes:
      # Enable this in dev only
      - ./philoagents-api/src/philoagents:/app/philoagents
      - ./philoagents-api/tools:/app/tools
    command: /app/.venv/bin/uvicorn philoagents.infrastructure.api:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - philoagents-network

  ui:
    container_name: philoagents-ui
    build:
      context: ./philoagents-ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./philoagents-ui:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - philoagents-network

networks:
  philoagents-network:
    name: philoagents-network
