services:
  - type: web
    name: philoagent-api
    env: docker
    rootDir: philoagents-api
    dockerfilePath: philoagents-api/Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: philoagent-ui
    env: docker
    rootDir: philoagents-ui
    dockerfilePath: philoagents-ui/Dockerfile
    envVars:
      - key: VITE_API_BASE_URL
        sync: false
